services:
  app:
    build:
      context: .
    image: ascp-app:dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ascp.rule=Host(`ascp.r4nol.dev`)"
      - "traefik.http.routers.ascp.entrypoints=websecure"
      - "traefik.http.routers.ascp.tls.certresolver=le"
      - "traefik.http.services.ascp.loadbalancer.server.port=8080"
    expose:
      - "8080"
    environment:
      APP_PORT: 8080
      SECURITY_LOG_DIR: /var/log/app
      APP_MODE: fixed
    tmpfs:
      - /tmp
      - /var/log/app:mode=0777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - global_network

networks:
  global_network:
    external: true
